import React, { useState, useEffect } from 'react';
import * as Icons from 'lucide-react';
import api from '../services/api';
import { useToastStore } from '../store/toastStore';

export type MetricType = 'calls' | 'hot_leads' | 'logins' | 'approved' | 'disbursed' | 'achievement';

interface MetricConfig {
  id: MetricType;
  label: string;
  shortLabel: string;
  iconName: string;
  badgeBg: string;
  badgeText: string;
  gradientFrom: string;
  gradientTo: string;
  description: string;
  unit: string;
}

const METRICS_CONFIG: MetricConfig[] = [
  {
    id: 'calls',
    label: '01. Calls Made',
    shortLabel: 'Calls Made',
    iconName: 'PhoneCall',
    badgeBg: 'bg-blue-50 dark:bg-blue-950/60',
    badgeText: 'text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-600',
    description: '12-Month dial breakdown of total phone calls made by each telecaller (Jan to Dec)',
    unit: 'Calls'
  },
  {
    id: 'hot_leads',
    label: '02. Hot Leads',
    shortLabel: 'Hot Leads',
    iconName: 'Flame',
    badgeBg: 'bg-rose-50 dark:bg-rose-950/60',
    badgeText: 'text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-red-600',
    description: '12-Month count of high-priority Hot Leads generated by each telecaller (Jan to Dec)',
    unit: 'Leads'
  },
  {
    id: 'logins',
    label: '03. Logins / Given Login',
    shortLabel: 'Logins',
    iconName: 'LogIn',
    badgeBg: 'bg-amber-50 dark:bg-amber-950/60',
    badgeText: 'text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    description: '12-Month count of file logins / given logins processed by each telecaller (Jan to Dec)',
    unit: 'Logins'
  },
  {
    id: 'approved',
    label: '04. Approved Cases',
    shortLabel: 'Approved',
    iconName: 'CheckCircle2',
    badgeBg: 'bg-emerald-50 dark:bg-emerald-950/60',
    badgeText: 'text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-teal-600',
    description: '12-Month count of approved loan cases by each telecaller (Jan to Dec)',
    unit: 'Approved'
  },
  {
    id: 'disbursed',
    label: '05. Disbursed Cases',
    shortLabel: 'Disbursed',
    iconName: 'Banknote',
    badgeBg: 'bg-purple-50 dark:bg-purple-950/60',
    badgeText: 'text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-violet-600',
    description: '12-Month count of disbursed loan cases by each telecaller (Jan to Dec)',
    unit: 'Disbursed'
  },
  {
    id: 'achievement',
    label: '06. Target Achievement %',
    shortLabel: 'Target %',
    iconName: 'Award',
    badgeBg: 'bg-yellow-50 dark:bg-yellow-950/60',
    badgeText: 'text-yellow-800 dark:text-yellow-300 border-yellow-300 dark:border-yellow-800',
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    description: '12-Month target-wise achievement percentage % for each telecaller (Jan to Dec)',
    unit: '%'
  }
];

// Helper to robustly parse DD-MM-YYYY, DD/MM/YYYY, YYYY-MM-DD, ISO & standard dates
const parseLeadDate = (val: any): Date | null => {
  if (!val) return null;
  if (val instanceof Date) return isNaN(val.getTime()) ? null : val;

  const s = String(val).trim();
  if (!s) return null;

  // Handles DD-MM-YYYY or DD/MM/YYYY e.g. "01-09-2026" or "01/09/2026"
  const ddmmyyyy = s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})/);
  if (ddmmyyyy) {
    const day = parseInt(ddmmyyyy[1], 10);
    const month = parseInt(ddmmyyyy[2], 10) - 1; // 0-indexed
    const year = parseInt(ddmmyyyy[3], 10);
    const parsed = new Date(year, month, day);
    if (!isNaN(parsed.getTime())) return parsed;
  }

  // Handles YYYY-MM-DD or YYYY/MM/DD
  const yyyymmdd = s.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);
  if (yyyymmdd) {
    const year = parseInt(yyyymmdd[1], 10);
    const month = parseInt(yyyymmdd[2], 10) - 1;
    const day = parseInt(yyyymmdd[3], 10);
    const parsed = new Date(year, month, day);
    if (!isNaN(parsed.getTime())) return parsed;
  }

  const standard = new Date(s);
  return isNaN(standard.getTime()) ? null : standard;
};

export default function TelecallerMonthlyPage() {
  const { showToast } = useToastStore();
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<any[]>([]);
  const [leads, setLeads] = useState<any[]>([]);
  const [selectedYear, setSelectedYear] = useState<string>(new Date().getFullYear().toString());
  const [activeMetric, setActiveMetric] = useState<MetricType>('calls');

  const monthNamesShort = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
  const monthNamesFull = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const years = ['2024', '2025', '2026', '2027'];

  useEffect(() => {
    fetchMonthlyData();
  }, []);

  const fetchMonthlyData = async () => {
    setLoading(true);
    try {
      const [usersRes, summaryRes, leadsRes] = await Promise.all([
        api.get('/auth/users?purpose=dropdown').catch(() => ({ data: [] })),
        api.get('/reports/telecaller-summary').catch(() => ({ data: { telecallers: [] } })),
        api.get('/records/leads?limit=5000').catch(() => ({ data: [] }))
      ]);

      const fetchedUsers = Array.isArray(usersRes.data) ? usersRes.data : usersRes.data?.users || [];
      const fetchedLeads = Array.isArray(leadsRes.data) ? leadsRes.data : leadsRes.data?.records || [];

      setUsers(fetchedUsers);
      setLeads(fetchedLeads);
    } catch (err) {
      console.error(err);
      showToast('Failed to load telecaller monthly report data.', 'error');
    } finally {
      setLoading(false);
    }
  };

  // Build full agent list from Users DB + any Lead assigned user (Ensures 100% of users are present)
  const allAgentsList = React.useMemo(() => {
    const list: { id: string; name: string; role: string; email: string; dailyTarget: number }[] = [];
    const addedKeys = new Set<string>();

    const addAgent = (id: string, name: string, role: string, email: string, dailyTarget: number = 50) => {
      const cleanName = String(name || '').trim();
      if (!cleanName) return;
      const key = cleanName.toLowerCase();
      if (!addedKeys.has(key)) {
        addedKeys.add(key);
        list.push({
          id: id || cleanName,
          name: cleanName,
          role: role || 'Telecaller',
          email: email || `${cleanName.toLowerCase().replace(/\s+/g, '')}@inkcrm.com`,
          dailyTarget: dailyTarget || 50
        });
      }
    };

    // 1. Add all registered users from DB
    users.forEach((u: any) => {
      const name = u.firstName ? `${u.firstName} ${u.lastName || ''}`.trim() : u.name || u.username || u.email?.split('@')[0] || 'Agent';
      addAgent(
        u._id || name,
        name,
        u.role?.name || u.role || 'Telecaller',
        u.email,
        u.dailyTarget || 50
      );
    });

    // 2. Add any agent referenced in leads data
    leads.forEach((l: any) => {
      const data = l.data || {};
      const candidateNames = [
        l.assignedTo?.name,
        data.telecaller,
        data.assignedAgent,
        data.assignedTo,
        l.assignedToName,
        data.createdBy,
        data.createdByName,
        data.assignedBy,
        data.assignedByName,
        data.psm
      ];

      candidateNames.forEach(cn => {
        if (cn && typeof cn === 'string' && cn.trim()) {
          addAgent(cn.trim(), cn.trim(), 'Telecaller', `${cn.trim().toLowerCase().replace(/\s+/g, '')}@inkcrm.com`, 50);
        }
      });
    });

    // Sort alphabetically by caller name
    list.sort((a, b) => a.name.localeCompare(b.name));
    return list;
  }, [users, leads]);

  // Robust Agent Matching helper
  const matchLeadAgent = (lead: any, agent: typeof allAgentsList[0]): boolean => {
    const data = lead.data || {};
    const norm = (val: any) => String(val || '').trim().toLowerCase();

    const aId = norm(agent.id);
    const aName = norm(agent.name);
    const aEmail = norm(agent.email);
    const aEmailPrefix = norm(agent.email.split('@')[0]);

    const candidates = [
      norm(lead.assignedTo?._id),
      norm(lead.assignedTo?.name),
      norm(lead.createdBy?._id),
      norm(lead.createdBy?.name),
      norm(data.assignedTo),
      norm(data.assignedToName),
      norm(data.assignedAgent),
      norm(data.telecaller),
      norm(data.createdBy),
      norm(data.createdByName),
      norm(data.assignedBy),
      norm(data.assignedByName),
      norm(data.psm),
      norm(data.source)
    ].filter(Boolean);

    return candidates.some(c => (
      c === aId ||
      c === aName ||
      c === aEmail ||
      c === aEmailPrefix ||
      (aName.length >= 3 && c.includes(aName)) ||
      (c.length >= 3 && aName.includes(c))
    ));
  };

  // Ultra-Comprehensive Metric Qualification helper
  const matchLeadMetric = (lead: any, metric: MetricType): boolean => {
    const data = lead.data || {};
    const st = String(data.status || data.dialStatus || data.normalizedStatus || lead.status || '').trim().toLowerCase();
    const caseDet = String(data.caseDetails || data.case_details || data.remarks || data.notes || '').trim().toLowerCase();
    const fullText = `${st} ${caseDet}`;

    switch (metric) {
      case 'calls': {
        const notDialed = ['yet to call', 'not called', 'new', ''];
        const isDialedStatus = st && !notDialed.includes(st);
        const hasCallAttempt = Number(data.callAttempts) > 0 || !!data.dialedAt || !!data.lastCallDate;
        return isDialedStatus || hasCallAttempt;
      }
      case 'hot_leads': {
        return fullText.includes('hot') || fullText.includes('warm') || fullText.includes('priority');
      }
      case 'logins': {
        return fullText.includes('login') || fullText.includes('logged') || fullText.includes('given login') || fullText.includes('underwriting');
      }
      case 'approved': {
        return fullText.includes('approv') || fullText.includes('sanction') || fullText.includes('pass') || fullText.includes('eligible');
      }
      case 'disbursed': {
        return fullText.includes('disburs') || fullText.includes('disbuse') || fullText.includes('paid') || fullText.includes('released');
      }
      case 'achievement': {
        const notDialed = ['yet to call', 'not called', 'new', ''];
        return (st && !notDialed.includes(st)) || Number(data.callAttempts) > 0 || !!data.dialedAt || !!data.lastCallDate;
      }
      default:
        return false;
    }
  };

  // Live Summary Totals for all 6 Metric Cards across Selected Year
  const metricTotals = React.useMemo(() => {
    const targetYearNum = parseInt(selectedYear, 10) || new Date().getFullYear();
    const counts: Record<MetricType, number> = {
      calls: 0,
      hot_leads: 0,
      logins: 0,
      approved: 0,
      disbursed: 0,
      achievement: 0
    };

    leads.forEach(l => {
      const data = l.data || {};
      const dateVal = data.dialedAt || data.lastCallDate || data.created_at || data.date || l.updatedAt || l.createdAt;
      const d = parseLeadDate(dateVal);
      if (!d || d.getFullYear() !== targetYearNum) return;

      if (matchLeadMetric(l, 'calls')) counts.calls++;
      if (matchLeadMetric(l, 'hot_leads')) counts.hot_leads++;
      if (matchLeadMetric(l, 'logins')) counts.logins++;
      if (matchLeadMetric(l, 'approved')) counts.approved++;
      if (matchLeadMetric(l, 'disbursed')) counts.disbursed++;
    });

    const targetBase = (allAgentsList.length || 1) * 50 * 25 * 12; // Annual target calls pool
    counts.achievement = targetBase > 0 ? Math.min(100, Math.round((counts.calls / targetBase) * 100)) : 0;

    return counts;
  }, [leads, selectedYear, allAgentsList]);

  // Compute 12-Month Performance Matrix for Active Metric (Caller Name x Jan-Dec Months)
  const monthlyMatrixData = React.useMemo(() => {
    const targetYearNum = parseInt(selectedYear, 10) || new Date().getFullYear();

    const agentMonthlyCounts = new Map<string, number[]>();
    allAgentsList.forEach(agent => {
      agentMonthlyCounts.set(agent.id, new Array(12).fill(0));
    });

    leads.forEach(l => {
      if (!matchLeadMetric(l, activeMetric)) return;

      const data = l.data || {};
      const dateVal = data.dialedAt || data.lastCallDate || data.created_at || data.date || l.updatedAt || l.createdAt;
      const leadDateObj = parseLeadDate(dateVal);
      if (!leadDateObj || leadDateObj.getFullYear() !== targetYearNum) return;

      const monthIdx = leadDateObj.getMonth(); // 0 to 11

      const matchedAgent = allAgentsList.find(a => matchLeadAgent(l, a));

      if (matchedAgent) {
        const counts = agentMonthlyCounts.get(matchedAgent.id) || new Array(12).fill(0);
        counts[monthIdx] = (counts[monthIdx] || 0) + 1;
        agentMonthlyCounts.set(matchedAgent.id, counts);
      }
    });

    // Construct matrix rows for EVERY SINGLE USER
    const matrixRows = allAgentsList.map(agent => {
      const rawCounts = agentMonthlyCounts.get(agent.id) || new Array(12).fill(0);
      
      const monthCounts = rawCounts.map((cnt, mIdx) => {
        if (activeMetric === 'achievement') {
          const daysInM = new Date(targetYearNum, mIdx + 1, 0).getDate();
          const target = (agent.dailyTarget || 50) * daysInM;
          return target > 0 ? Math.min(100, Math.round((cnt / target) * 100)) : 0;
        }
        return cnt;
      });

      const totalOrAnnual = activeMetric === 'achievement'
        ? Math.min(100, Math.round((rawCounts.reduce((a, b) => a + b, 0) / ((agent.dailyTarget || 50) * 300)) * 100))
        : rawCounts.reduce((a, b) => a + b, 0);

      const avgPerMonth = activeMetric === 'achievement'
        ? Math.round(monthCounts.reduce((a, b) => a + b, 0) / 12)
        : Math.round(totalOrAnnual / 12);

      return {
        agentId: agent.id,
        callerName: agent.name,
        role: agent.role,
        rawCounts,
        monthCounts,
        annualTotal: totalOrAnnual,
        avgPerMonth
      };
    });

    // Sort rows by Annual Total descending
    matrixRows.sort((a, b) => b.annualTotal - a.annualTotal || a.callerName.localeCompare(b.callerName));

    // Calculate Column Monthly Totals
    const monthlyTotals = new Array(12).fill(0);
    let grandAnnualTotal = 0;

    matrixRows.forEach(row => {
      row.monthCounts.forEach((val, mIdx) => {
        monthlyTotals[mIdx] += val;
      });
      grandAnnualTotal += row.annualTotal;
    });

    // Determine Top Performer & Top Month
    const topPerformerRow = matrixRows[0];
    let topMonthIdx = 0;
    let maxMonthVal = 0;

    monthlyTotals.forEach((val, mIdx) => {
      if (val > maxMonthVal) {
        maxMonthVal = val;
        topMonthIdx = mIdx;
      }
    });

    const activeCfg = METRICS_CONFIG.find(m => m.id === activeMetric) || METRICS_CONFIG[0];

    return {
      yearStr: selectedYear,
      matrixRows,
      monthlyTotals,
      grandAnnualTotal,
      overallMonthlyAvg: Math.round(grandAnnualTotal / 12),
      topPerformer: topPerformerRow ? `${topPerformerRow.callerName} (${activeMetric === 'achievement' ? `${topPerformerRow.annualTotal}%` : `${topPerformerRow.annualTotal} ${activeCfg.unit}`})` : 'N/A',
      topMonthName: maxMonthVal > 0 ? `${monthNamesFull[topMonthIdx]} (${activeMetric === 'achievement' ? `${maxMonthVal}%` : `${maxMonthVal} ${activeCfg.unit}`})` : 'N/A'
    };
  }, [allAgentsList, leads, selectedYear, activeMetric]);

  // Export 12-Month Matrix to Excel for Active Metric
  const export12MonthExcel = async (metricId: MetricType) => {
    const XLSX = await import('xlsx');
    const metricCfg = METRICS_CONFIG.find(m => m.id === metricId) || METRICS_CONFIG[0];
    const { yearStr, matrixRows, monthlyTotals, grandAnnualTotal, overallMonthlyAvg } = monthlyMatrixData;
    
    const workbook = XLSX.utils.book_new();

    const totalColHeader = metricId === 'achievement' ? 'Annual Achievement %' : `Annual ${metricCfg.unit}`;
    const headers = ['Caller Name', ...monthNamesShort, totalColHeader, 'Avg / Month'];
    
    const dataRows = matrixRows.map(row => {
      const rowObj: Record<string, any> = { 'Caller Name': row.callerName };
      monthNamesShort.forEach((m, mIdx) => {
        const val = row.monthCounts[mIdx];
        if (metricId === 'achievement') {
          rowObj[m] = val > 0 ? `${val}%` : '';
        } else {
          rowObj[m] = val > 0 ? val : '';
        }
      });
      rowObj[totalColHeader] = metricId === 'achievement' ? `${row.annualTotal}%` : row.annualTotal;
      rowObj['Avg / Month'] = metricId === 'achievement' ? `${row.avgPerMonth}%` : row.avgPerMonth;
      return rowObj;
    });

    // Add summary row
    const summaryRow: Record<string, any> = { 'Caller Name': `TOTAL MONTHLY ${metricCfg.unit.toUpperCase()}` };
    monthNamesShort.forEach((m, mIdx) => {
      const val = monthlyTotals[mIdx];
      summaryRow[m] = metricId === 'achievement' ? `${val}%` : val;
    });
    summaryRow[totalColHeader] = metricId === 'achievement' ? `${grandAnnualTotal}%` : grandAnnualTotal;
    summaryRow['Avg / Month'] = metricId === 'achievement' ? `${overallMonthlyAvg}%` : overallMonthlyAvg;
    dataRows.push(summaryRow);

    const worksheet = XLSX.utils.json_to_sheet(dataRows, { header: headers });
    worksheet['!cols'] = headers.map(h => ({ wch: h === 'Caller Name' ? 26 : h === totalColHeader ? 22 : 12 }));
    XLSX.utils.book_append_sheet(workbook, worksheet, `12Month_${metricCfg.shortLabel.replace(/\s+/g, '_')}`);

    const fileName = `Telecaller_Monthly_${metricCfg.shortLabel.replace(/[^a-zA-Z0-9]/g, '_')}_Report_${yearStr}.xlsx`;
    XLSX.writeFile(workbook, fileName);
    showToast(`Exported 12-Month ${metricCfg.label} Excel Report for ${yearStr}!`, 'success');
  };

  const activeConfig = METRICS_CONFIG.find(m => m.id === activeMetric) || METRICS_CONFIG[0];

  const renderMetricIcon = (iconName: string, className: string = "w-5 h-5") => {
    switch (iconName) {
      case 'PhoneCall': return <Icons.PhoneCall className={className} />;
      case 'Flame': return <Icons.Flame className={className} />;
      case 'LogIn': return <Icons.LogIn className={className} />;
      case 'CheckCircle2': return <Icons.CheckCircle2 className={className} />;
      case 'Banknote': return <Icons.Banknote className={className} />;
      case 'Award': return <Icons.Award className={className} />;
      default: return <Icons.BarChart3 className={className} />;
    }
  };

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto text-left px-4 md:px-8 py-4">
      {/* ── TOP HEADER BANNER ────────────────────────────────────────────── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/90 dark:border-slate-800 pb-5">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-indigo-600 via-purple-600 to-amber-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/25 flex-shrink-0">
            <Icons.Calendar className="w-6 h-6 stroke-[2.2]" />
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white uppercase tracking-tight">
              Telecaller's Monthly 12-Month Performance Reports
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              Annual 12-Month matrix (Jan - Dec) across all {allAgentsList.length} users for Calls, Hot Leads, Logins, Approved, Disbursed & Target %
            </p>
          </div>
        </div>

        {/* Global Export Excel Button for Active Metric */}
        <button
          onClick={() => export12MonthExcel(activeMetric)}
          className="h-11 px-5 bg-gradient-to-r from-indigo-600 via-purple-600 to-amber-600 hover:opacity-95 text-white text-xs font-black uppercase tracking-wider rounded-xl shadow-lg shadow-indigo-600/25 transition-all flex items-center justify-center gap-2.5 cursor-pointer flex-shrink-0 active:scale-95"
        >
          <Icons.FileSpreadsheet className="w-4 h-4" />
          <span>Export Monthly {activeConfig.shortLabel} Excel</span>
        </button>
      </div>

      {/* ── 6-METRIC SECTION CONTROLLER TILES WITH DEDICATED ICONS ───────── */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
        {METRICS_CONFIG.map((cfg) => {
          const isActive = activeMetric === cfg.id;
          const totalVal = metricTotals[cfg.id];

          return (
            <div
              key={cfg.id}
              onClick={() => setActiveMetric(cfg.id)}
              className={`p-4 rounded-2xl border transition-all duration-200 cursor-pointer relative overflow-hidden text-left flex flex-col justify-between group ${
                isActive
                  ? 'bg-white dark:bg-slate-900 border-indigo-500 dark:border-indigo-400 shadow-lg ring-2 ring-indigo-500/20'
                  : 'bg-white/80 dark:bg-slate-900/80 border-slate-200/90 dark:border-slate-800 hover:border-indigo-300 dark:hover:border-slate-700 hover:shadow-xs'
              }`}
            >
              <div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${cfg.gradientFrom} ${cfg.gradientTo} ${isActive ? 'opacity-100' : 'opacity-40 group-hover:opacity-100'} transition-opacity`} />
              
              <div className="flex items-center justify-between gap-2 mb-2">
                <span className={`text-[10px] font-black uppercase tracking-wider ${isActive ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-500 dark:text-slate-400'}`}>
                  {cfg.shortLabel}
                </span>
                <div className={`w-7 h-7 rounded-lg flex items-center justify-center transition-transform group-hover:scale-110 ${
                  isActive 
                    ? `bg-gradient-to-tr ${cfg.gradientFrom} ${cfg.gradientTo} text-white shadow-xs`
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'
                }`}>
                  {renderMetricIcon(cfg.iconName, "w-3.5 h-3.5")}
                </div>
              </div>

              <div className="mt-1">
                <div className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white font-mono leading-none">
                  {cfg.id === 'achievement' ? `${totalVal}%` : totalVal.toLocaleString()}
                </div>
                <div className="flex items-center justify-between mt-2 pt-2 border-t border-slate-100 dark:border-slate-800/80">
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${cfg.badgeBg} ${cfg.badgeText}`}>
                    {cfg.unit} Annual
                  </span>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      export12MonthExcel(cfg.id);
                    }}
                    title={`Export ${cfg.shortLabel} Excel`}
                    className="text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 p-0.5 rounded transition-colors"
                  >
                    <Icons.Download className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── 4 SUMMARY KPI CARDS FOR ACTIVE METRIC ───────────────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Card 1: Top Performer */}
        <div className="bg-white dark:bg-slate-900 border border-amber-100 dark:border-slate-800 rounded-2xl p-5 shadow-xs relative overflow-hidden text-left hover:shadow-md transition-all">
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-amber-500 to-yellow-500" />
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Top Performer ({selectedYear})
            </span>
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-amber-500 to-yellow-500 flex items-center justify-center text-white shadow-xs">
              <Icons.Trophy className="w-4.5 h-4.5" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-lg font-black text-slate-900 dark:text-white truncate">
              {monthlyMatrixData.topPerformer}
            </span>
          </div>
        </div>

        {/* Card 2: Annual Metric Total */}
        <div className="bg-white dark:bg-slate-900 border border-emerald-100 dark:border-slate-800 rounded-2xl p-5 shadow-xs relative overflow-hidden text-left hover:shadow-md transition-all">
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-500 to-teal-500" />
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Annual Total ({activeConfig.unit})
            </span>
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-emerald-500 to-teal-600 flex items-center justify-center text-white shadow-xs">
              {renderMetricIcon(activeConfig.iconName, "w-4.5 h-4.5")}
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-black text-slate-900 dark:text-white font-mono">
              {activeMetric === 'achievement' ? `${monthlyMatrixData.grandAnnualTotal}%` : monthlyMatrixData.grandAnnualTotal.toLocaleString()}
            </span>
            <span className="text-[11px] font-bold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/50 px-2 py-0.5 rounded-md font-mono">
              Year {selectedYear}
            </span>
          </div>
        </div>

        {/* Card 3: Top Month */}
        <div className="bg-white dark:bg-slate-900 border border-sky-100 dark:border-slate-800 rounded-2xl p-5 shadow-xs relative overflow-hidden text-left hover:shadow-md transition-all">
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-sky-500 to-blue-500" />
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Top Month
            </span>
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-sky-500 to-blue-600 flex items-center justify-center text-white shadow-xs">
              <Icons.CalendarDays className="w-4.5 h-4.5" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-lg font-black text-slate-900 dark:text-white truncate">
              {monthlyMatrixData.topMonthName}
            </span>
          </div>
        </div>

        {/* Card 4: Monthly Average */}
        <div className="bg-white dark:bg-slate-900 border border-indigo-100 dark:border-slate-800 rounded-2xl p-5 shadow-xs relative overflow-hidden text-left hover:shadow-md transition-all">
          <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500 to-violet-500" />
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
              Monthly Average
            </span>
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 to-violet-500 flex items-center justify-center text-white shadow-xs">
              <Icons.TrendingUp className="w-4.5 h-4.5" />
            </div>
          </div>
          <div className="mt-3 flex items-baseline gap-2">
            <span className="text-2xl font-black text-slate-900 dark:text-white font-mono">
              {activeMetric === 'achievement' ? `${monthlyMatrixData.overallMonthlyAvg}%` : monthlyMatrixData.overallMonthlyAvg.toLocaleString()}
            </span>
            <span className="text-[11px] font-bold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/50 px-2 py-0.5 rounded-md font-mono">
              Avg / Month
            </span>
          </div>
        </div>
      </div>

      {/* ── 12-MONTH PERFORMANCE MATRIX TABLE (FOR ALL USERS) ─────────────── */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 rounded-2xl overflow-hidden shadow-xs relative">
        <div className={`absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r ${activeConfig.gradientFrom} ${activeConfig.gradientTo}`} />
        
        {/* Header Bar */}
        <div className="p-5 sm:p-6 pb-4 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl bg-gradient-to-tr ${activeConfig.gradientFrom} ${activeConfig.gradientTo} text-white flex items-center justify-center shadow-md flex-shrink-0`}>
              {renderMetricIcon(activeConfig.iconName, "w-5 h-5")}
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-black text-slate-900 dark:text-white uppercase tracking-tight flex items-center gap-2">
                12-Month {activeConfig.label} ({selectedYear})
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                {activeConfig.description} across all {allAgentsList.length} users
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3 flex-wrap">
            {/* Select Year Dropdown */}
            <div className="flex items-center gap-2 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 px-3 py-1.5 rounded-xl">
              <span className="text-xs font-bold uppercase text-slate-500">Year:</span>
              <select
                value={selectedYear}
                onChange={(e) => setSelectedYear(e.target.value)}
                className="bg-transparent text-xs font-black text-slate-900 dark:text-white focus:outline-none cursor-pointer font-mono"
              >
                {years.map(y => (
                  <option key={y} value={y} className="bg-white dark:bg-slate-800 text-slate-900 dark:text-white">
                    {y}
                  </option>
                ))}
              </select>
            </div>

            {/* Export Button */}
            <button
              onClick={() => export12MonthExcel(activeMetric)}
              className="h-10 px-4 bg-indigo-600 hover:bg-indigo-700 active:scale-[0.98] text-white text-xs font-extrabold uppercase tracking-wider rounded-xl shadow-md shadow-indigo-500/25 transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Icons.FileSpreadsheet className="w-4 h-4" />
              <span>Export {activeConfig.shortLabel} Excel</span>
            </button>
          </div>
        </div>

        {/* Table Content */}
        {loading ? (
          <div className="p-16 text-center text-xs text-slate-400 font-semibold flex items-center justify-center gap-2">
            <Icons.Loader className="w-5 h-5 animate-spin text-indigo-600" />
            <span>Loading 12-Month Performance Matrix...</span>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse min-w-[1100px]">
              <thead>
                <tr className="bg-[#000080] text-white text-[11px] font-black uppercase tracking-wider h-11">
                  <th className="py-3 px-4 sticky left-0 z-10 bg-[#000080] border-r border-indigo-900 min-w-[200px] shadow-sm">
                    Caller Name ({allAgentsList.length} Users)
                  </th>
                  {monthNamesShort.map((m) => (
                    <th key={m} className="py-3 px-3 text-center border-r border-indigo-900 min-w-[70px] whitespace-nowrap font-mono">
                      {m}
                    </th>
                  ))}
                  <th className="py-3 px-4 text-center bg-indigo-950 min-w-[120px] whitespace-nowrap border-r border-indigo-900">
                    {activeMetric === 'achievement' ? 'Annual %' : `Annual ${activeConfig.unit}`}
                  </th>
                  <th className="py-3 px-4 text-center bg-indigo-950 min-w-[100px] whitespace-nowrap">
                    Avg / Mo
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
                {monthlyMatrixData.matrixRows.map((row, idx) => (
                  <tr 
                    key={row.agentId || idx} 
                    className={`${idx % 2 === 0 ? 'bg-slate-50/70 dark:bg-slate-900/60' : 'bg-white dark:bg-slate-900'} hover:bg-indigo-50/50 dark:hover:bg-slate-800/60 transition-colors h-12`}
                  >
                    {/* Caller Name Column */}
                    <td className={`py-3 px-4 font-bold text-slate-900 dark:text-slate-100 sticky left-0 z-10 border-r border-slate-200 dark:border-slate-800 shadow-sm ${idx % 2 === 0 ? 'bg-slate-100/90 dark:bg-slate-850' : 'bg-slate-50 dark:bg-slate-900'}`}>
                      <div className="flex items-center gap-2.5">
                        <div className="w-7 h-7 rounded-lg bg-indigo-600 text-white flex items-center justify-center font-black text-[11px] uppercase flex-shrink-0">
                          {row.callerName.substring(0, 2)}
                        </div>
                        <span className="capitalize block truncate max-w-[160px]" title={row.callerName}>
                          {row.callerName}
                        </span>
                      </div>
                    </td>

                    {/* 12 Months Columns */}
                    {row.monthCounts.map((val, mIdx) => (
                      <td 
                        key={mIdx} 
                        className="py-3 px-3 text-center border-r border-slate-200/60 dark:border-slate-800/60 font-mono text-xs"
                      >
                        {val > 0 ? (
                          <span className={`font-extrabold px-2 py-0.5 rounded-md border ${
                            activeMetric === 'achievement'
                              ? 'text-emerald-700 dark:text-emerald-300 bg-emerald-50 dark:bg-emerald-950/60 border-emerald-200/60 dark:border-emerald-800/60'
                              : 'text-slate-900 dark:text-slate-100 bg-indigo-50 dark:bg-indigo-950/60 border-indigo-200/60 dark:border-indigo-800/60'
                          }`}>
                            {activeMetric === 'achievement' ? `${val}%` : val}
                          </span>
                        ) : (
                          <span className="text-slate-300 dark:text-slate-700">-</span>
                        )}
                      </td>
                    ))}

                    {/* Annual Total Column */}
                    <td className="py-3 px-4 text-center font-mono font-black text-indigo-700 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-950/40 border-r border-slate-200 dark:border-slate-800 text-xs">
                      {row.annualTotal > 0 ? (
                        <span className="px-2.5 py-1 rounded-lg bg-indigo-600 text-white shadow-3xs">
                          {activeMetric === 'achievement' ? `${row.annualTotal}%` : row.annualTotal}
                        </span>
                      ) : (
                        <span className="text-slate-400 font-normal">0</span>
                      )}
                    </td>

                    {/* Avg / Month Column */}
                    <td className="py-3 px-4 text-center font-mono font-bold text-teal-700 dark:text-teal-400 bg-teal-50/40 dark:bg-teal-950/30 text-xs">
                      {activeMetric === 'achievement' ? `${row.avgPerMonth}%` : row.avgPerMonth}
                    </td>
                  </tr>
                ))}

                {monthlyMatrixData.matrixRows.length === 0 && (
                  <tr>
                    <td colSpan={15} className="py-14 text-center text-slate-400">
                      No telecaller performance records found for Year {selectedYear}.
                    </td>
                  </tr>
                )}
              </tbody>

              {/* Bottom Grand Summary Row */}
              {monthlyMatrixData.matrixRows.length > 0 && (
                <tfoot>
                  <tr className="bg-slate-100 dark:bg-slate-800 font-black text-slate-900 dark:text-white border-t-2 border-slate-300 dark:border-slate-700 h-12">
                    <td className="py-3 px-4 sticky left-0 z-10 bg-slate-200 dark:bg-slate-750 border-r border-slate-300 dark:border-slate-700 uppercase tracking-wider font-extrabold text-[11px]">
                      TOTAL MONTHLY {activeConfig.unit.toUpperCase()}
                    </td>

                    {monthlyMatrixData.monthlyTotals.map((tot, mIdx) => (
                      <td key={mIdx} className="py-3 px-3 text-center border-r border-slate-300 dark:border-slate-700 font-mono text-xs font-black text-indigo-700 dark:text-indigo-300">
                        {activeMetric === 'achievement' ? `${tot}%` : (tot > 0 ? tot : 0)}
                      </td>
                    ))}

                    <td className="py-3 px-4 text-center font-mono font-black text-white bg-indigo-700 border-r border-indigo-800 text-sm">
                      {activeMetric === 'achievement' ? `${monthlyMatrixData.grandAnnualTotal}%` : monthlyMatrixData.grandAnnualTotal}
                    </td>

                    <td className="py-3 px-4 text-center font-mono font-black text-white bg-teal-700 text-xs">
                      {activeMetric === 'achievement' ? `${monthlyMatrixData.overallMonthlyAvg}%` : monthlyMatrixData.overallMonthlyAvg}
                    </td>
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
