import React, { useState, useEffect } from 'react';
import * as Icons from 'lucide-react';
import api from '../services/api';
import { useToastStore } from '../store/toastStore';
import MultiSelectDropdown from '../components/MultiSelectDropdown';

export type MetricType = 'calls' | 'hot_leads' | 'logins' | 'approved' | 'disbursed' | 'achievement';

interface MetricConfig {
  id: MetricType;
  label: string;
  shortLabel: string;
  iconName: string;
  badgeBg: string;
  badgeText: string;
  gradientFrom: string;
  gradientTo: string;
  description: string;
  unit: string;
}

const METRICS_CONFIG: MetricConfig[] = [
  {
    id: 'calls',
    label: '01. Calls Made',
    shortLabel: 'Calls Made',
    iconName: 'PhoneCall',
    badgeBg: 'bg-blue-50 dark:bg-blue-950/60',
    badgeText: 'text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-600',
    description: 'Daily dial breakdown of total phone calls made by each telecaller',
    unit: 'Calls'
  },
  {
    id: 'hot_leads',
    label: '02. Hot Leads',
    shortLabel: 'Hot Leads',
    iconName: 'Flame',
    badgeBg: 'bg-rose-50 dark:bg-rose-950/60',
    badgeText: 'text-rose-700 dark:text-rose-300 border-rose-200 dark:border-rose-800',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-red-600',
    description: 'Daily count of high-priority Hot Leads generated by each telecaller',
    unit: 'Leads'
  },
  {
    id: 'logins',
    label: '03. Logins / Given Login',
    shortLabel: 'Logins',
    iconName: 'LogIn',
    badgeBg: 'bg-amber-50 dark:bg-amber-950/60',
    badgeText: 'text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-800',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    description: 'Daily count of file logins / given logins processed by each telecaller',
    unit: 'Logins'
  },
  {
    id: 'approved',
    label: '04. Approved Cases',
    shortLabel: 'Approved',
    iconName: 'CheckCircle2',
    badgeBg: 'bg-emerald-50 dark:bg-emerald-950/60',
    badgeText: 'text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-teal-600',
    description: 'Daily count of approved loan cases by each telecaller',
    unit: 'Approved'
  },
  {
    id: 'disbursed',
    label: '05. Disbursed Cases',
    shortLabel: 'Disbursed',
    iconName: 'Banknote',
    badgeBg: 'bg-purple-50 dark:bg-purple-950/60',
    badgeText: 'text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-violet-600',
    description: 'Daily count of disbursed loan cases by each telecaller',
    unit: 'Disbursed'
  },
  {
    id: 'achievement',
    label: '06. Target Achievement %',
    shortLabel: 'Target %',
    iconName: 'Award',
    badgeBg: 'bg-yellow-50 dark:bg-yellow-950/60',
    badgeText: 'text-yellow-800 dark:text-yellow-300 border-yellow-300 dark:border-yellow-800',
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    description: 'Daily target-wise achievement percentage % for each telecaller',
    unit: '%'
  }
];

// Helper to robustly parse DD-MM-YYYY, DD/MM/YYYY, YYYY-MM-DD, ISO & standard dates
const parseLeadDate = (val: any): Date | null => {
  if (!val) return null;
  if (val instanceof Date) return isNaN(val.getTime()) ? null : val;

  const s = String(val).trim();
  if (!s) return null;

  const standard = new Date(s);
  if (!isNaN(standard.getTime())) return standard;

  // Handles DD-MM-YYYY or DD/MM/YYYY e.g. "01-09-2026" or "01/09/2026"
  const ddmmyyyy = s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})/);
  if (ddmmyyyy) {
    const day = parseInt(ddmmyyyy[1], 10);
    const month = parseInt(ddmmyyyy[2], 10) - 1; // 0-indexed
    const year = parseInt(ddmmyyyy[3], 10);
    const parsed = new Date(year, month, day);
    if (!isNaN(parsed.getTime())) return parsed;
  }

  // Handles YYYY-MM-DD or YYYY/MM/DD
  const yyyymmdd = s.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);
  if (yyyymmdd) {
    const year = parseInt(yyyymmdd[1], 10);
    const month = parseInt(yyyymmdd[2], 10) - 1;
    const day = parseInt(yyyymmdd[3], 10);
    const parsed = new Date(year, month, day);
    if (!isNaN(parsed.getTime())) return parsed;
  }

  return null;
};

export default function TelecallerReportsPage() {
  const { showToast } = useToastStore();
  const [loading, setLoading] = useState(false);
  const [users, setUsers] = useState<any[]>([]);
  const [leads, setLeads] = useState<any[]>([]);
  const [activeMetric, setActiveMetric] = useState<MetricType>('calls');

  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const years = ['2024', '2025', '2026', '2027'];

  // Month & Year Filter State (Defaulting to empty = All Months & Years)
  const [selectedMonths, setSelectedMonths] = useState<string[]>([]);
  const [selectedYears, setSelectedYears] = useState<string[]>([]);

  useEffect(() => {
    fetchInitialData();
  }, []);

  const fetchInitialData = async () => {
    setLoading(true);
    try {
      const [usersRes, summaryRes, leadsRes] = await Promise.all([
        api.get('/auth/users?purpose=dropdown').catch(() => ({ data: [] })),
        api.get('/reports/telecaller-summary').catch(() => ({ data: { telecallers: [] } })),
        api.get('/records/leads?limit=5000').catch(() => ({ data: [] }))
      ]);

      const fetchedUsers = Array.isArray(usersRes.data) ? usersRes.data : usersRes.data?.users || [];
      const fetchedLeads = Array.isArray(leadsRes.data) ? leadsRes.data : leadsRes.data?.records || [];

      setUsers(fetchedUsers);
      setLeads(fetchedLeads);
    } catch (err) {
      console.error(err);
      showToast('Failed to load telecaller report data.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleFilterClick = () => {
    fetchInitialData();
    showToast('Updated report with selected month and year filters.', 'info');
  };

  // Build full agent list from Users DB + any Lead assigned user (Ensures 100% of users are present)
  const allAgentsList = React.useMemo(() => {
    const list: { id: string; name: string; role: string; email: string; dailyTarget: number }[] = [];
    const addedKeys = new Set<string>();

    const addAgent = (id: string, name: string, role: string, email: string, dailyTarget: number = 50) => {
      const cleanName = String(name || '').trim();
      if (!cleanName) return;
      const key = cleanName.toLowerCase();
      if (!addedKeys.has(key)) {
        addedKeys.add(key);
        list.push({
          id: id || cleanName,
          name: cleanName,
          role: role || 'Telecaller',
          email: email || `${cleanName.toLowerCase().replace(/\s+/g, '')}@inkcrm.com`,
          dailyTarget: dailyTarget || 50
        });
      }
    };

    // 1. Add all registered users from DB
    users.forEach((u: any) => {
      const name = u.firstName ? `${u.firstName} ${u.lastName || ''}`.trim() : u.name || u.username || u.email?.split('@')[0] || 'Agent';
      addAgent(
        u._id || name,
        name,
        u.role?.name || u.role || 'Telecaller',
        u.email,
        u.dailyTarget || 50
      );
    });

    // 2. Add any agent referenced in leads data
    leads.forEach((l: any) => {
      const data = l.data || {};
      const candidateNames = [
        l.assignedTo?.name,
        data.telecaller,
        data.assignedAgent,
        data.assignedTo,
        l.assignedToName,
        data.createdBy,
        data.createdByName,
        data.assignedBy,
        data.assignedByName,
        data.psm
      ];

      candidateNames.forEach(cn => {
        if (cn && typeof cn === 'string' && cn.trim()) {
          addAgent(cn.trim(), cn.trim(), 'Telecaller', `${cn.trim().toLowerCase().replace(/\s+/g, '')}@inkcrm.com`, 50);
        }
      });
    });

    // Sort alphabetically by caller name
    list.sort((a, b) => a.name.localeCompare(b.name));
    return list;
  }, [users, leads]);

  // Robust Agent Matching helper
  const matchLeadAgent = (lead: any, agent: typeof allAgentsList[0]): boolean => {
    const data = lead.data || {};
    const norm = (val: any) => String(val || '').trim().toLowerCase();

    const aId = norm(agent.id);
    const aName = norm(agent.name);
    const aEmail = norm(agent.email);
    const aEmailPrefix = norm(agent.email.split('@')[0]);

    const candidates = [
      norm(lead.assignedTo?._id),
      norm(lead.assignedTo?.name),
      norm(lead.createdBy?._id),
      norm(lead.createdBy?.name),
      norm(data.assignedTo),
      norm(data.assignedToName),
      norm(data.assignedAgent),
      norm(data.telecaller),
      norm(data.createdBy),
      norm(data.createdByName),
      norm(data.assignedBy),
      norm(data.assignedByName),
      norm(data.psm),
      norm(data.source)
    ].filter(Boolean);

    return candidates.some(c => (
      c === aId ||
      c === aName ||
      c === aEmail ||
      c === aEmailPrefix ||
      (aName.length >= 3 && c.includes(aName)) ||
      (c.length >= 3 && aName.includes(c))
    ));
  };

  // Ultra-Comprehensive Metric Qualification helper
  const matchLeadMetric = (lead: any, metric: MetricType): boolean => {
    const data = lead.data || {};
    const st = String(data.status || data.dialStatus || data.normalizedStatus || lead.status || '').trim().toLowerCase();
    const caseDet = String(data.caseDetails || data.case_details || data.remarks || data.notes || '').trim().toLowerCase();
    const fullText = `${st} ${caseDet}`;

    switch (metric) {
      case 'calls': {
        const notDialed = ['yet to call', 'not called', 'new', ''];
        const isDialedStatus = st && !notDialed.includes(st);
        const hasCallAttempt = Number(data.callAttempts) > 0 || !!data.dialedAt || !!data.lastCallDate;
        return isDialedStatus || hasCallAttempt;
      }
      case 'hot_leads': {
        return fullText.includes('hot') || fullText.includes('warm') || fullText.includes('priority');
      }
      case 'logins': {
        return fullText.includes('login') || fullText.includes('logged') || fullText.includes('given login') || fullText.includes('underwriting');
      }
      case 'approved': {
        return fullText.includes('approv') || fullText.includes('sanction') || fullText.includes('pass') || fullText.includes('eligible');
      }
      case 'disbursed': {
        return fullText.includes('disburs') || fullText.includes('disbuse') || fullText.includes('paid') || fullText.includes('released');
      }
      case 'achievement': {
        const notDialed = ['yet to call', 'not called', 'new', ''];
        return (st && !notDialed.includes(st)) || Number(data.callAttempts) > 0 || !!data.dialedAt || !!data.lastCallDate;
      }
      default:
        return false;
    }
  };

  // Live Summary Totals for all 6 Metrics Cards across filtered agents
  const metricTotals = React.useMemo(() => {
    const counts: Record<MetricType, number> = {
      calls: 0,
      hot_leads: 0,
      logins: 0,
      approved: 0,
      disbursed: 0,
      achievement: 0
    };

    leads.forEach(l => {
      const data = l.data || {};
      const dateVal = data.dialedAt || data.lastCallDate || data.created_at || data.date || l.updatedAt || l.createdAt;
      const d = parseLeadDate(dateVal);
      if (!d) return;

      const monthName = months[d.getMonth()];
      const yearStr = d.getFullYear().toString();

      if (selectedMonths.length > 0 && !selectedMonths.includes(monthName)) return;
      if (selectedYears.length > 0 && !selectedYears.includes(yearStr)) return;

      if (matchLeadMetric(l, 'calls')) counts.calls++;
      if (matchLeadMetric(l, 'hot_leads')) counts.hot_leads++;
      if (matchLeadMetric(l, 'logins')) counts.logins++;
      if (matchLeadMetric(l, 'approved')) counts.approved++;
      if (matchLeadMetric(l, 'disbursed')) counts.disbursed++;
    });

    const targetBase = (allAgentsList.length || 1) * 50 * 25; // Monthly call pool base
    counts.achievement = targetBase > 0 ? Math.min(100, Math.round((counts.calls / targetBase) * 100)) : 0;

    return counts;
  }, [leads, selectedMonths, selectedYears, allAgentsList]);

  // Date-wise & Day-of-Week Monthly Telecaller Matrix (Dynamic for Active Metric)
  const dateWiseMatrix = React.useMemo(() => {
    const targetMonthName = selectedMonths[0] || months[new Date().getMonth()];
    const targetYearStr = selectedYears[0] || new Date().getFullYear().toString();
    const monthIndex = months.findIndex(m => m.toLowerCase() === targetMonthName.toLowerCase());
    const yearNum = parseInt(targetYearStr, 10);

    const safeMonth = monthIndex >= 0 ? monthIndex : new Date().getMonth();
    const safeYear = !isNaN(yearNum) ? yearNum : new Date().getFullYear();

    const daysInMonth = new Date(safeYear, safeMonth + 1, 0).getDate();

    const daysOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    const daysOfWeekShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

    const dateHeaders: { key: string; label: string; dayNum: number; dayName: string; dayNameShort: string }[] = [];
    for (let d = 1; d <= daysInMonth; d++) {
      const dayStr = String(d).padStart(2, '0');
      const monthStr = String(safeMonth + 1).padStart(2, '0');
      const isoKey = `${safeYear}-${monthStr}-${dayStr}`;
      
      const dateObj = new Date(safeYear, safeMonth, d);
      const dayIdx = dateObj.getDay();
      const dayName = daysOfWeek[dayIdx];
      const dayNameShort = daysOfWeekShort[dayIdx];

      const headerLabel = `${dayStr}-${monthStr}-${safeYear} (${dayNameShort})`;
      dateHeaders.push({ key: isoKey, label: headerLabel, dayNum: d, dayName, dayNameShort });
    }

    const agentMetricCounts = new Map<string, Map<string, number>>();
    allAgentsList.forEach(agent => {
      agentMetricCounts.set(agent.id, new Map<string, number>());
    });

    leads.forEach(l => {
      if (!matchLeadMetric(l, activeMetric)) return;

      const data = l.data || {};
      const dateVal = data.dialedAt || data.lastCallDate || data.created_at || data.date || l.updatedAt || l.createdAt;
      const leadDate = parseLeadDate(dateVal);
      if (!leadDate) return;

      if (leadDate.getMonth() !== safeMonth || leadDate.getFullYear() !== safeYear) return;

      const isoKey = leadDate.toISOString().slice(0, 10);

      const matchedAgent = allAgentsList.find(a => matchLeadAgent(l, a));

      if (matchedAgent) {
        const countsMap = agentMetricCounts.get(matchedAgent.id) || new Map<string, number>();
        countsMap.set(isoKey, (countsMap.get(isoKey) || 0) + 1);
        agentMetricCounts.set(matchedAgent.id, countsMap);
      }
    });

    // 1. Daily Date Rows for EVERY SINGLE USER
    const matrixRows = allAgentsList.map(agent => {
      const countsMap = agentMetricCounts.get(agent.id) || new Map<string, number>();
      let totalValue = 0;
      const dailyCounts: Record<string, number> = {};

      dateHeaders.forEach(dh => {
        const cnt = countsMap.get(dh.key) || 0;
        
        if (activeMetric === 'achievement') {
          const dailyTarget = agent.dailyTarget || 50;
          const pct = dailyTarget > 0 ? Math.min(100, Math.round((cnt / dailyTarget) * 100)) : 0;
          dailyCounts[dh.label] = pct;
          totalValue += cnt;
        } else {
          dailyCounts[dh.label] = cnt;
          totalValue += cnt;
        }
      });

      let overallTotalOrPct = totalValue;
      if (activeMetric === 'achievement') {
        const totalMonthlyTarget = (agent.dailyTarget || 50) * daysInMonth;
        overallTotalOrPct = totalMonthlyTarget > 0 ? Math.min(100, Math.round((totalValue / totalMonthlyTarget) * 100)) : 0;
      }

      return {
        agentId: agent.id,
        callerName: agent.name,
        role: agent.role,
        dailyCounts,
        totalValue: overallTotalOrPct
      };
    });

    // 2. Day of Week Summary Rows
    const dowMatrixRows = allAgentsList.map(agent => {
      const countsMap = agentMetricCounts.get(agent.id) || new Map<string, number>();
      const dowCounts: Record<string, number> = {
        'Sunday': 0,
        'Monday': 0,
        'Tuesday': 0,
        'Wednesday': 0,
        'Thursday': 0,
        'Friday': 0,
        'Saturday': 0
      };
      let totalValue = 0;

      dateHeaders.forEach(dh => {
        const cnt = countsMap.get(dh.key) || 0;
        dowCounts[dh.dayName] = (dowCounts[dh.dayName] || 0) + cnt;
        totalValue += cnt;
      });

      return {
        agentId: agent.id,
        callerName: agent.name,
        dowCounts,
        totalValue
      };
    });

    return {
      monthName: targetMonthName,
      yearStr: targetYearStr,
      dateHeaders,
      matrixRows,
      dowMatrixRows
    };
  }, [allAgentsList, leads, selectedMonths, selectedYears, activeMetric]);

  // Dedicated Per-Section Excel Exporter
  const handleExportMetricExcel = async (metricId: MetricType) => {
    const XLSX = await import('xlsx');
    const metricCfg = METRICS_CONFIG.find(m => m.id === metricId) || METRICS_CONFIG[0];
    const { monthName, yearStr, dateHeaders, matrixRows, dowMatrixRows } = dateWiseMatrix;
    
    const workbook = XLSX.utils.book_new();

    // Sheet 1: Daily Date-Wise Matrix
    const totalColHeader = metricId === 'achievement' ? 'Overall Achievement %' : `Total ${metricCfg.unit}`;
    const headers1 = ['Caller Name', ...dateHeaders.map(dh => dh.label), totalColHeader];
    
    const dataRows1 = matrixRows.map(row => {
      const rowObj: Record<string, any> = { 'Caller Name': row.callerName };
      dateHeaders.forEach(dh => {
        const val = row.dailyCounts[dh.label];
        if (metricId === 'achievement') {
          rowObj[dh.label] = val > 0 ? `${val}%` : '';
        } else {
          rowObj[dh.label] = val > 0 ? val : '';
        }
      });
      rowObj[totalColHeader] = metricId === 'achievement' ? `${row.totalValue}%` : row.totalValue;
      return rowObj;
    });

    const worksheet1 = XLSX.utils.json_to_sheet(dataRows1, { header: headers1 });
    worksheet1['!cols'] = headers1.map(h => ({ wch: h === 'Caller Name' ? 26 : h === totalColHeader ? 22 : 16 }));
    XLSX.utils.book_append_sheet(workbook, worksheet1, `Daily_${metricCfg.shortLabel.replace(/\s+/g, '_')}_Matrix`);

    // Sheet 2: Day of Week Summary Matrix
    const headers2 = ['Caller Name', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', totalColHeader];
    const dataRows2 = dowMatrixRows.map(row => {
      const rowObj: Record<string, any> = { 'Caller Name': row.callerName };
      ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].forEach(day => {
        const cnt = row.dowCounts[day];
        rowObj[day] = cnt > 0 ? cnt : '';
      });
      rowObj[totalColHeader] = metricId === 'achievement' ? `${row.totalValue}%` : row.totalValue;
      return rowObj;
    });

    const worksheet2 = XLSX.utils.json_to_sheet(dataRows2, { header: headers2 });
    worksheet2['!cols'] = headers2.map(h => ({ wch: h === 'Caller Name' ? 26 : 14 }));
    XLSX.utils.book_append_sheet(workbook, worksheet2, 'Day_of_Week_Summary');

    const fileName = `Telecaller_${metricCfg.shortLabel.replace(/[^a-zA-Z0-9]/g, '_')}_Report_${monthName}_${yearStr}.xlsx`;
    XLSX.writeFile(workbook, fileName);
    showToast(`Exported ${metricCfg.label} Excel Report for ${monthName} ${yearStr}!`, 'success');
  };

  const activeConfig = METRICS_CONFIG.find(m => m.id === activeMetric) || METRICS_CONFIG[0];

  const renderMetricIcon = (iconName: string, className: string = "w-5 h-5") => {
    switch (iconName) {
      case 'PhoneCall': return <Icons.PhoneCall className={className} />;
      case 'Flame': return <Icons.Flame className={className} />;
      case 'LogIn': return <Icons.LogIn className={className} />;
      case 'CheckCircle2': return <Icons.CheckCircle2 className={className} />;
      case 'Banknote': return <Icons.Banknote className={className} />;
      case 'Award': return <Icons.Award className={className} />;
      default: return <Icons.BarChart3 className={className} />;
    }
  };

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto text-left px-4 md:px-8 py-4">
      {/* ── TOP HEADER BANNER ────────────────────────────────────────────── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/90 dark:border-slate-800 pb-5">
        <div className="flex items-center gap-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-indigo-600 via-purple-600 to-rose-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/25 flex-shrink-0">
            <Icons.PhoneCall className="w-6 h-6 stroke-[2.2]" />
          </div>
          <div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white uppercase tracking-tight">
              Telecaller's Multi-Metric Performance Reports
            </h1>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5 font-medium">
              Comprehensive report matrix across all {allAgentsList.length} users/telecallers
            </p>
          </div>
        </div>

        {/* Global Export Excel Button for Active Metric */}
        <button
          onClick={() => handleExportMetricExcel(activeMetric)}
          className="h-11 px-5 bg-gradient-to-r from-indigo-600 via-purple-600 to-rose-600 hover:opacity-95 text-white text-xs font-black uppercase tracking-wider rounded-xl shadow-lg shadow-indigo-600/25 transition-all flex items-center justify-center gap-2.5 cursor-pointer flex-shrink-0 active:scale-95"
        >
          <Icons.FileSpreadsheet className="w-4 h-4" />
          <span>Export {activeConfig.shortLabel} Excel</span>
        </button>
      </div>

      {/* ── 6-METRIC SECTION CONTROLLER TILES WITH DEDICATED ICONS ───────── */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
        {METRICS_CONFIG.map((cfg) => {
          const isActive = activeMetric === cfg.id;
          const totalVal = metricTotals[cfg.id];

          return (
            <div
              key={cfg.id}
              onClick={() => setActiveMetric(cfg.id)}
              className={`p-4 rounded-2xl border transition-all duration-200 cursor-pointer relative overflow-hidden text-left flex flex-col justify-between group ${
                isActive
                  ? 'bg-white dark:bg-slate-900 border-indigo-500 dark:border-indigo-400 shadow-lg ring-2 ring-indigo-500/20'
                  : 'bg-white/80 dark:bg-slate-900/80 border-slate-200/90 dark:border-slate-800 hover:border-indigo-300 dark:hover:border-slate-700 hover:shadow-xs'
              }`}
            >
              <div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${cfg.gradientFrom} ${cfg.gradientTo} ${isActive ? 'opacity-100' : 'opacity-40 group-hover:opacity-100'} transition-opacity`} />
              
              <div className="flex items-center justify-between gap-2 mb-2">
                <span className={`text-[10px] font-black uppercase tracking-wider ${isActive ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-500 dark:text-slate-400'}`}>
                  {cfg.shortLabel}
                </span>
                <div className={`w-7 h-7 rounded-lg flex items-center justify-center transition-transform group-hover:scale-110 ${
                  isActive 
                    ? `bg-gradient-to-tr ${cfg.gradientFrom} ${cfg.gradientTo} text-white shadow-xs`
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'
                }`}>
                  {renderMetricIcon(cfg.iconName, "w-3.5 h-3.5")}
                </div>
              </div>

              <div className="mt-1">
                <div className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white font-mono leading-none">
                  {cfg.id === 'achievement' ? `${totalVal}%` : totalVal.toLocaleString()}
                </div>
                <div className="flex items-center justify-between mt-2 pt-2 border-t border-slate-100 dark:border-slate-800/80">
                  <span className={`text-[9.5px] font-bold px-2 py-0.5 rounded-full border ${cfg.badgeBg} ${cfg.badgeText}`}>
                    {cfg.unit} Report
                  </span>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleExportMetricExcel(cfg.id);
                    }}
                    title={`Export ${cfg.shortLabel} Excel`}
                    className="text-slate-400 hover:text-indigo-600 dark:hover:text-indigo-400 p-0.5 rounded transition-colors"
                  >
                    <Icons.Download className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* ── FILTER PARAMETERS CARD ───────────────────────────────────────── */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 rounded-2xl p-5 sm:p-6 shadow-xs relative overflow-visible z-20 space-y-4">
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500" />
        
        <div className="flex items-center justify-between gap-3 pb-3 border-b border-slate-100 dark:border-slate-800">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
              <Icons.SlidersHorizontal className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-xs font-black text-slate-800 dark:text-slate-200 uppercase tracking-wider">
                Report Filter Parameters
              </h3>
              <p className="text-[11px] text-slate-500">Filter metrics across all {allAgentsList.length} users by month and year</p>
            </div>
          </div>

          <button
            onClick={handleFilterClick}
            className="h-9 px-5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold uppercase tracking-wider rounded-xl shadow-md shadow-indigo-600/20 transition-all flex items-center justify-center gap-2 cursor-pointer"
          >
            <Icons.CheckCircle className="w-3.5 h-3.5" />
            <span>Apply Filter</span>
          </button>
        </div>

        {/* SELECT MONTH & SELECT YEAR FILTERS */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <MultiSelectDropdown
            label="Select Month"
            options={months}
            selectedValues={selectedMonths}
            onChange={setSelectedMonths}
            placeholder="-All Months-"
          />

          <MultiSelectDropdown
            label="Select Year"
            options={years}
            selectedValues={selectedYears}
            onChange={setSelectedYears}
            placeholder="-All Years-"
          />
        </div>
      </div>

      {/* ── ACTIVE METRIC PERFORMANCE MATRIX TABLE (FOR ALL USERS) ───────── */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 rounded-2xl overflow-hidden shadow-xs relative">
        <div className={`absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r ${activeConfig.gradientFrom} ${activeConfig.gradientTo}`} />
        
        <div className="p-5 sm:p-6 pb-4 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl bg-gradient-to-tr ${activeConfig.gradientFrom} ${activeConfig.gradientTo} text-white flex items-center justify-center shadow-md flex-shrink-0`}>
              {renderMetricIcon(activeConfig.iconName, "w-5 h-5")}
            </div>
            <div>
              <h3 className="text-base font-black text-slate-900 dark:text-white uppercase tracking-tight flex items-center gap-2">
                Date-Wise {activeConfig.label} ({dateWiseMatrix.monthName} {dateWiseMatrix.yearStr})
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                {activeConfig.description} across all {allAgentsList.length} users (Day 1 to Day {dateWiseMatrix.dateHeaders.length})
              </p>
            </div>
          </div>

          <button
            onClick={() => handleExportMetricExcel(activeMetric)}
            className="h-10 px-5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold uppercase tracking-wider rounded-xl shadow-md shadow-indigo-500/20 transition-all flex items-center justify-center gap-2 cursor-pointer self-start sm:self-auto"
          >
            <Icons.FileSpreadsheet className="w-4 h-4" />
            <span>Export {activeConfig.shortLabel} Excel</span>
          </button>
        </div>

        {loading ? (
          <div className="p-14 text-center text-xs text-slate-400">Loading daily metric matrix for all users...</div>
        ) : (
          <div className="overflow-x-auto border-t border-slate-200 dark:border-slate-800">
            <table className="w-full text-left text-xs border-collapse min-w-[1200px]">
              <thead>
                <tr className="bg-[#000080] text-white text-[11px] font-black uppercase tracking-wider h-11">
                  <th className="py-3 px-4 sticky left-0 z-10 bg-[#000080] border-r border-indigo-900 min-w-[200px] shadow-sm">
                    Caller Name ({allAgentsList.length} Users)
                  </th>
                  {dateWiseMatrix.dateHeaders.map(dh => (
                    <th key={dh.key} className="py-3 px-3 text-center border-r border-indigo-900 min-w-[90px] whitespace-nowrap font-mono">
                      {dh.label}
                    </th>
                  ))}
                  <th className="py-3 px-4 text-center bg-indigo-950 min-w-[120px] whitespace-nowrap">
                    {activeMetric === 'achievement' ? 'Month Achievement %' : `Total ${activeConfig.unit}`}
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
                {dateWiseMatrix.matrixRows.map((row, idx) => (
                  <tr 
                    key={row.agentId || idx} 
                    className={`${idx % 2 === 0 ? 'bg-slate-50/70 dark:bg-slate-900/60' : 'bg-white dark:bg-slate-900'} hover:bg-indigo-50/50 dark:hover:bg-slate-800/60 transition-colors h-11`}
                  >
                    {/* Sticky Caller Name Column */}
                    <td className={`py-2.5 px-4 font-bold text-slate-900 dark:text-slate-100 sticky left-0 z-10 border-r border-slate-200 dark:border-slate-800 shadow-sm ${idx % 2 === 0 ? 'bg-slate-100/90 dark:bg-slate-850' : 'bg-slate-50 dark:bg-slate-900'}`}>
                      <span className="capitalize block truncate max-w-[190px]" title={row.callerName}>
                        {row.callerName}
                      </span>
                    </td>

                    {/* Daily Metric Counts */}
                    {dateWiseMatrix.dateHeaders.map(dh => {
                      const count = row.dailyCounts[dh.label];
                      return (
                        <td 
                          key={dh.key} 
                          className="py-2.5 px-3 text-center border-r border-slate-200/60 dark:border-slate-800/60 font-mono text-xs"
                        >
                          {count > 0 ? (
                            <span className={`font-extrabold ${activeMetric === 'achievement' ? 'text-emerald-600 dark:text-emerald-400' : 'text-slate-800 dark:text-slate-200'}`}>
                              {activeMetric === 'achievement' ? `${count}%` : count}
                            </span>
                          ) : (
                            <span className="text-slate-300 dark:text-slate-700">-</span>
                          )}
                        </td>
                      );
                    })}

                    {/* Overall Total / Achievement Column */}
                    <td className="py-2.5 px-4 text-center font-mono font-black text-indigo-700 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-950/40">
                      {activeMetric === 'achievement' ? `${row.totalValue}%` : (row.totalValue > 0 ? row.totalValue : 0)}
                    </td>
                  </tr>
                ))}

                {dateWiseMatrix.matrixRows.length === 0 && (
                  <tr>
                    <td colSpan={dateWiseMatrix.dateHeaders.length + 2} className="py-12 text-center text-slate-400">
                      No telecaller data available for the selected month and year.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
